import { OnInit } from '@angular/core';
import { LiveChatWidgetApiModel } from './livechat-widget.models';
import { Subject } from 'rxjs';
export declare class LivechatWidgetComponent implements OnInit {
    licenseId: number;
    group: number;
    chatBetweenGroups: boolean;
    params: {
        name: string;
        value: any;
    };
    visitor: {
        name: string;
        email: string;
    };
    gaVersion: string;
    onChatLoaded: Subject<LiveChatWidgetApiModel>;
    onAfterLoad: Subject<{}>;
    onBeforeLoad: Subject<{}>;
    onChatEnded: Subject<{}>;
    onChatStarted: Subject<any>;
    onChatStateChanged: Subject<any>;
    onChatWindowHidden: Subject<{}>;
    onChatWindowMinimized: Subject<{}>;
    onChatWindowOpened: Subject<{}>;
    data: any;
    onMessage: Subject<any>;
    onPostchatSurveySubmitted: Subject<any>;
    onPrechatSurveySubmitted: Subject<any>;
    onRatingCommentSubmitted: Subject<any>;
    onRatingSubmitted: Subject<any>;
    onTicketCreated: Subject<any>;
    onWidgetResize: Subject<{}>;
    agentsAreAvailable: Function;
    chatRunning: Function;
    chatWindowHidden: Function;
    chatWindowMaximized: Function;
    chatWindowMinimized: Function;
    closeChat: Function;
    getChatId: Function;
    getChatsNumber: Function;
    getLastVisitTimestamp: Function;
    getPageViewsNumber: Function;
    getVisitorId: Function;
    getVisitsNumber: Function;
    hideChatWindow: Function;
    minimizeChatWindow: Function;
    openChatWindow: Function;
    setCustomVariables: Function;
    setVisitorEmail: Function;
    setVisitorName: Function;
    triggerSalesTracker: Function;
    updateCustomVariables: Function;
    visitorEngaged: Function;
    visitorQueued: Function;
    constructor();
    ngOnInit(): void;
    private _chatLoaded;
    private _setCallbacks;
    private _setMethods;
}
